## Hyperparameter tunning using grid search cv

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('banknotes.csv')
df.head()

   Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [4]:
# iloc used select specific colum and row
x= df.iloc[:,:-1]
x[:2]

   Variance  Skewness  Curtosis  Entropy
0    3.6216    8.6661   -2.8073 -0.44699
1    4.5459    8.1674   -2.4586 -1.46210

In [6]:
y = df['Class'] # to select class column
y[:2]

0    0
1    0
Name: Class, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.2)

In [8]:
from sklearn.tree import DecisionTreeClassifier

In [10]:
DecisionTreeClassifier?

In [11]:
# lets use a DT model with default parameter
m1 = DecisionTreeClassifier()
m1.fit(x_train,y_train)
print(m1.score(x_train,y_train)*100)
print(m1.score(x_test,y_test)*100)

100.0
98.9090909090909

In [14]:
m2 = DecisionTreeClassifier(criterion='entropy',
    splitter='random',
    max_depth=4,
    min_samples_split=2,
    min_samples_leaf=2,
    min_weight_fraction_leaf=0.5)
m2.fit(x_train,y_train)
print(m2.score(x_train,y_train)*100)
print(m2.score(x_test,y_test)*100)

56.15314494074749
53.090909090909086

In [ ]:
# In HyperParamter tuning following algorithms we can prefer
# - GridSearchCV
# - RandomizedSearchCV

In [15]:
from sklearn.model_selection import GridSearchCV

In [16]:
GridSearchCV?

In [ ]:
"""
GridSearchCV(
    estimator,--> object of algorithm
    param_grid,---> dict of parameter and its multiple options

GridSearchCV(m1,pr_grid)
m1: ML model =SVC()
pr_grid: parameter grid in the form of dict= see below example
"""

In [17]:
pr_grid = {
    'criterion':['gini','entropy','log_loss'],
    'splitter':['best','random'],
    'max_depth':[2,3,4,5,6,8],
    'min_samples_split':[2,3],
    'min_samples_leaf':[1,2,3,4,5],
    'min_weight_fraction_leaf':[0.0,0.2,0.4,0.5]
    }

In [18]:
pr_grid

{'criterion': ['gini', 'entropy', 'log_loss'],
 'splitter': ['best', 'random'],
 'max_depth': [2, 3, 4, 5, 6, 8],
 'min_samples_split': [2, 3],
 'min_samples_leaf': [1, 2, 3, 4, 5],
 'min_weight_fraction_leaf': [0.0, 0.2, 0.4, 0.5]}

In [19]:
"""
GridSearchCV(
    estimator,
    param_grid,
"""
#model = DecisionTreeClassifier()
print(m1)
#lets create an object of GridSearchCV
out = GridSearchCV(m1,pr_grid)

DecisionTreeClassifier()

In [20]:
 # noraml we prefer 10 fold cross calidation i mean cv=10
from sklearn.model_selection import cross_val_score
cross_val_score(m1,x,y).mean()

np.float64(0.9810537491705376)

In [21]:
cross_val_score(m1,x,y,cv=10).mean()

np.float64(0.9839627631439756)

In [23]:
out

GridSearchCV(estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': [2, 3, 4, 5, 6, 8],
                         'min_samples_leaf': [1, 2, 3, 4, 5],
                         'min_samples_split': [2, 3],
                         'min_weight_fraction_leaf': [0.0, 0.2, 0.4, 0.5],
                         'splitter': ['best', 'random']})

In [ ]:
x[:2]

In [ ]:
y[:2]

In [24]:
# Train ove X and Y using GridSearchCV object
out.fit(x,y)

GridSearchCV(estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': [2, 3, 4, 5, 6, 8],
                         'min_samples_leaf': [1, 2, 3, 4, 5],
                         'min_samples_split': [2, 3],
                         'min_weight_fraction_leaf': [0.0, 0.2, 0.4, 0.5],
                         'splitter': ['best', 'random']})

In [25]:
pr_grid

{'criterion': ['gini', 'entropy', 'log_loss'],
 'splitter': ['best', 'random'],
 'max_depth': [2, 3, 4, 5, 6, 8],
 'min_samples_split': [2, 3],
 'min_samples_leaf': [1, 2, 3, 4, 5],
 'min_weight_fraction_leaf': [0.0, 0.2, 0.4, 0.5]}

In [26]:
out.best_params_

{'criterion': 'entropy',
 'max_depth': 8,
 'min_samples_leaf': 1,
 'min_samples_split': 3,
 'min_weight_fraction_leaf': 0.0,
 'splitter': 'best'}

In [27]:
out.best_estimator_

DecisionTreeClassifier(criterion='entropy', max_depth=8, min_samples_split=3)

In [28]:
# after getting best estimators build final ML model
final = DecisionTreeClassifier(criterion='entropy', max_depth=8)

In [29]:
final.fit(x,y)

DecisionTreeClassifier(criterion='entropy', max_depth=8)

In [30]:
final.score(x,y)*100

100.0

In [31]:
final.score(x_train,y_train)*100

100.0

In [32]:
final.score(x_test,y_test)*100

100.0

# use m2 model and pr_grid to apply gridsearchCV

In [33]:
m2

DecisionTreeClassifier(criterion='entropy', max_depth=4, min_samples_leaf=2,
                       min_weight_fraction_leaf=0.5, splitter='random')

In [34]:
pr_grid

{'criterion': ['gini', 'entropy', 'log_loss'],
 'splitter': ['best', 'random'],
 'max_depth': [2, 3, 4, 5, 6, 8],
 'min_samples_split': [2, 3],
 'min_samples_leaf': [1, 2, 3, 4, 5],
 'min_weight_fraction_leaf': [0.0, 0.2, 0.4, 0.5]}

In [35]:
# Assignment: Apply RandomizedSearchCV
from sklearn.model_selection import RandomizedSearchCV

In [36]:
RandomizedSearchCV?